### ISSUE TITLE
Single DB cluster

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/aws-cloudformation-database-cluster#9]
Guess the title says it all :)
Whats the chance of this as the current 3up implementation is a bit more than we require both pricing and scale.

**Comment by docktermj** [comment]
Hi @christianswanepoel 

I'll check in with our folks on that.

You are always welcome to create your own Cloudformations to create a simpler deployment.  

As you can imagine, we took the tact of creating a robust implementation that folks could scale back, rather than create a simple implementation that folks would have to figure out how to scale up.

**Comment by christianswanepoel** [comment]
Hi @docktermj 
The issue with rolling our own is hooking it up to the Senzing System Install Cloudformation(?)

**Comment by docktermj** [comment]
@christianswanepoel You've got me thinking about this.

Supposing you collapsed https://github.com/Senzing/aws-cloudformation-database-cluster/blob/main/cloudformation.yaml to one database, (i.e. delete `RdsDbClusterLibfeat`, `RdsDbClusterRes`, and related resources).  You would then modify

https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/eafa27829b0a7a8d736d4f2af13c28161e811f91/cloudformation.yaml#L324-L379

To point to the single database, instead of 3 databases.  For example,

```yaml
          {
              "PIPELINE": {
                  "CONFIGPATH": "/etc/opt/senzing",
                  "RESOURCEPATH": "/opt/senzing/g2/resources",
                  "SUPPORTPATH": "/opt/senzing/data"
              },
              "SQL": {
                  "CONNECTION":"postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHost}:${DatabasePort}:${DatabaseName}"
              },
          }
        - DatabaseHost:
            Fn::ImportValue:
              Fn::Sub: '${DatabaseStack}-database-host-core'
          DatabaseName:
            Fn::ImportValue:
              Fn::Sub: '${DatabaseStack}-database-name'
          DatabasePassword:
            Fn::ImportValue:
              Fn::Sub: '${DatabaseStack}-database-password'
          DatabasePort:
            Fn::ImportValue:
              Fn::Sub: '${DatabaseStack}-database-port-core'
          DatabaseUsername:
            Fn::ImportValue:
              Fn::Sub: '${DatabaseStack}-database-username'
```

I haven't actually tried, that.  But it's the approach I would take and tweek until it worked.

**Comment by docktermj** [comment]
@christianswanepoel Just an update:

Your request for a single database is getting traction.  Nothing in the works yet, but we're finding more folks desiring this feature.

**Comment by docktermj** [comment]
@roncewind Let's use this issue to figure out how to present the user with 1 or 3 databases.   I'll assign this issue to you.

**Comment by docktermj** [comment]
@roncewind We may actually want to start a new repository, perhaps `aws-cloudformation-database ` so that the "cluster" in the title doesn't confuse folks.   Once it is ready, we can then mark this repository as deprecated.

**Comment by christianswanepoel** [comment]
Will you post in this thread if the new repro is created?

> @roncewind We may actually want to start a new repository, perhaps `aws-cloudformation-database ` so that the "cluster" in the title doesn't confuse folks. Once it is ready, we can then mark this repository as deprecated.

**Comment by docktermj** [comment]
@christianswanepoel Yes.   We'll also put up a deprecation notice on this repository.

**Comment by roncewind** [comment]
@docktermj The new Cloudformation is created and tested.  Please advise on how you'd like to handle the repos.

**Comment by docktermj** [comment]
@roncewind  (and @christianswanepoel )

Here's my current thinking.  See if you can find a flaw in it...

1. Push the changes to the existing https://github.com/Senzing/aws-cloudformation-database-cluster
1. In the next 10 days or so, we rename the repository to "aws-cloudformation-database"   (GitHub will redirect old URLs)
1. We update the documentation for the new name of the repository.

I'm thinking of doing it this way because:
1. It keeps all of the history
2. It doesn't introduce confusion for a deprecated "aws-cloudformation-database-cluster" repository.

Any better ideas?

**Comment by roncewind** [comment]
PR merged

**Comment by roncewind** [comment]
@christianswanepoel You should have the ability to choose a single database in this Cloudformation now.  Let us know if you have any issues.  Thanks!
